export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG";
export const CHANGE_SHOW_SONG = "player/CHANGE_SHOW_SONG";
export const CHANGE_SHOW_SONG_COMMENTS = "player/CHANGE_SHOW_SONG_COMMENTS";
export const CHANGE_SHOW_SONG_LYRIC = "player/CHANGE_SHOW_SONG_LYRIC"