export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG";
export const CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_SONG_INDEX = "player/CHANGE_CURRENT_SONG_INDEX";

export const CHANGE_IS_PLAYING = "player/CHANGE_IS_PLAYING";
export const CHANGE_PROGRESS = "player/CHANGE_PROGRESS";
export const CHANGE_BUFFERED_PERCENT = "player/CHANGE_BUFFERED_PERCENT";
export const CHANGE_CURRENT_TIME_MS = "player/CHANGE_CURRENT_TIME_MS";